# Generated by Django 3.0.4 on 2020-03-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='totp_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appkey', models.CharField(max_length=32)),
                ('token', models.CharField(max_length=16)),
                ('user_id', models.IntegerField(default=0)),
            ],
        ),
    ]
