# Generated by Django 3.0.4 on 2020-03-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='totp_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=64)),
                ('token', models.CharField(max_length=16)),
                ('ip', models.CharField(max_length=150, unique=True)),
                ('update_time', models.IntegerField(default=0)),
            ],
        ),
    ]
