# Generated by Django 3.0.4 on 2020-03-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totp_user',
            name='appkey',
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
